export const excalidrawInitialData = {
    elements: [
        // Background Group Box
        {
            id: 'el_pipeline_group',
            type: 'rectangle',
            x: 230,
            y: 60,
            width: 560,
            height: 240,
            backgroundColor: '#1e1e2e05',
            strokeColor: '#bac2de',
            strokeStyle: 'dashed',
            strokeWidth: 1,
            roughness: 0.5,
            opacity: 100,
        },
        {
            id: 'txt_pipeline_group',
            type: 'text',
            x: 250,
            y: 75,
            text: 'Pipeline Core (CLI Creator Tools)',
            fontSize: 14,
            fontFamily: 1,
            strokeColor: '#585b70',
        },

        // Inputs
        {
            id: 'el_pr_history',
            type: 'ellipse',
            x: 50,
            y: 90,
            width: 140,
            height: 80,
            backgroundColor: '#cba6f7',
            strokeColor: '#1e1e2e',
            fillStyle: 'hachure',
            strokeWidth: 2,
            roughness: 1,
            opacity: 100,
            boundElements: [{ id: 'txt_pr_history', type: 'text' }],
        },
        {
            id: 'txt_pr_history',
            type: 'text',
            containerId: 'el_pr_history',
            x: 50,
            y: 90,
            width: 140,
            height: 80,
            text: 'PR History',
            fontSize: 18,
            fontFamily: 1,
            textAlign: 'center',
            verticalAlign: 'middle',
            strokeColor: '#1e1e2e',
        },
        {
            id: 'el_diff_hunks',
            type: 'ellipse',
            x: 50,
            y: 190,
            width: 140,
            height: 80,
            backgroundColor: '#f5e0dc',
            strokeColor: '#1e1e2e',
            fillStyle: 'hachure',
            strokeWidth: 2,
            roughness: 1,
            opacity: 100,
            boundElements: [{ id: 'txt_diff_hunks', type: 'text' }],
        },
        {
            id: 'txt_diff_hunks',
            type: 'text',
            containerId: 'el_diff_hunks',
            x: 50,
            y: 190,
            width: 140,
            height: 80,
            text: 'Diff Hunks',
            fontSize: 18,
            fontFamily: 1,
            textAlign: 'center',
            verticalAlign: 'middle',
            strokeColor: '#1e1e2e',
        },

        // Arrows from Inputs to Extraction
        {
            id: 'arrow_input1',
            type: 'arrow',
            x: 190,
            y: 130,
            width: 60,
            height: 20,
            strokeColor: '#1e1e2e',
            strokeWidth: 2,
            roughness: 1,
            points: [
                [0, 0],
                [30, 20],
                [60, 20],
            ],
        },
        {
            id: 'arrow_input2',
            type: 'arrow',
            x: 190,
            y: 230,
            width: 60,
            height: -80,
            strokeColor: '#1e1e2e',
            strokeWidth: 2,
            roughness: 1,
            points: [
                [0, 0],
                [30, -80],
                [60, -80],
            ],
        },

        // Pipeline Step 1: Extraction
        {
            id: 'el_extraction',
            type: 'rectangle',
            x: 250,
            y: 110,
            width: 110,
            height: 80,
            backgroundColor: '#fab387',
            strokeColor: '#1e1e2e',
            fillStyle: 'hachure',
            strokeWidth: 2,
            roughness: 1,
            opacity: 100,
            boundElements: [{ id: 'txt_extraction', type: 'text' }],
        },
        {
            id: 'txt_extraction',
            type: 'text',
            containerId: 'el_extraction',
            x: 250,
            y: 110,
            width: 110,
            height: 80,
            text: 'Extraction',
            fontSize: 16,
            fontFamily: 1,
            textAlign: 'center',
            verticalAlign: 'middle',
            strokeColor: '#1e1e2e',
        },
        {
            id: 'arrow_ext',
            type: 'arrow',
            x: 360,
            y: 150,
            width: 30,
            height: 0,
            strokeColor: '#1e1e2e',
            strokeWidth: 2,
            roughness: 1,
            points: [
                [0, 0],
                [30, 0],
            ],
        },

        // Pipeline Step 2: Weighting
        {
            id: 'el_weighting',
            type: 'rectangle',
            x: 390,
            y: 110,
            width: 110,
            height: 80,
            backgroundColor: '#f9e2af',
            strokeColor: '#1e1e2e',
            fillStyle: 'hachure',
            strokeWidth: 2,
            roughness: 1,
            opacity: 100,
            boundElements: [{ id: 'txt_weighting', type: 'text' }],
        },
        {
            id: 'txt_weighting',
            type: 'text',
            containerId: 'el_weighting',
            x: 390,
            y: 110,
            width: 110,
            height: 80,
            text: 'Weighting',
            fontSize: 16,
            fontFamily: 1,
            textAlign: 'center',
            verticalAlign: 'middle',
            strokeColor: '#1e1e2e',
        },
        {
            id: 'arrow_weight',
            type: 'arrow',
            x: 500,
            y: 150,
            width: 30,
            height: 0,
            strokeColor: '#1e1e2e',
            strokeWidth: 2,
            roughness: 1,
            points: [
                [0, 0],
                [30, 0],
            ],
        },

        // Pipeline Step 3: Synthesis
        {
            id: 'el_synthesis',
            type: 'rectangle',
            x: 530,
            y: 110,
            width: 110,
            height: 80,
            backgroundColor: '#a6e3a1',
            strokeColor: '#1e1e2e',
            fillStyle: 'hachure',
            strokeWidth: 2,
            roughness: 1,
            opacity: 100,
            boundElements: [{ id: 'txt_synthesis', type: 'text' }],
        },
        {
            id: 'txt_synthesis',
            type: 'text',
            containerId: 'el_synthesis',
            x: 530,
            y: 110,
            width: 110,
            height: 80,
            text: 'Synthesis',
            fontSize: 16,
            fontFamily: 1,
            textAlign: 'center',
            verticalAlign: 'middle',
            strokeColor: '#1e1e2e',
        },
        {
            id: 'arrow_synth',
            type: 'arrow',
            x: 640,
            y: 150,
            width: 30,
            height: 0,
            strokeColor: '#1e1e2e',
            strokeWidth: 2,
            roughness: 1,
            points: [
                [0, 0],
                [30, 0],
            ],
        },

        // Pipeline Step 4: Merging
        {
            id: 'el_merging',
            type: 'rectangle',
            x: 670,
            y: 110,
            width: 110,
            height: 80,
            backgroundColor: '#89b4fa',
            strokeColor: '#1e1e2e',
            fillStyle: 'hachure',
            strokeWidth: 2,
            roughness: 1,
            opacity: 100,
            boundElements: [{ id: 'txt_merging', type: 'text' }],
        },
        {
            id: 'txt_merging',
            type: 'text',
            containerId: 'el_merging',
            x: 670,
            y: 110,
            width: 110,
            height: 80,
            text: 'Merging',
            fontSize: 16,
            fontFamily: 1,
            textAlign: 'center',
            verticalAlign: 'middle',
            strokeColor: '#1e1e2e',
        },

        // Arrows from Merging to Outputs
        {
            id: 'arrow_output1',
            type: 'arrow',
            x: 780,
            y: 150,
            width: 50,
            height: -35,
            strokeColor: '#1e1e2e',
            strokeWidth: 2,
            roughness: 1,
            points: [
                [0, 0],
                [25, -35],
                [50, -55],
            ],
        },
        {
            id: 'arrow_output2',
            type: 'arrow',
            x: 780,
            y: 150,
            width: 50,
            height: 35,
            strokeColor: '#1e1e2e',
            strokeWidth: 2,
            roughness: 1,
            points: [
                [0, 0],
                [25, 35],
                [50, 55],
            ],
        },

        // Outputs
        {
            id: 'el_standards',
            type: 'rectangle',
            x: 830,
            y: 60,
            width: 140,
            height: 70,
            backgroundColor: '#f38ba8',
            strokeColor: '#1e1e2e',
            fillStyle: 'hachure',
            strokeWidth: 2,
            roughness: 1,
            opacity: 100,
            boundElements: [{ id: 'txt_standards', type: 'text' }],
        },
        {
            id: 'txt_standards',
            type: 'text',
            containerId: 'el_standards',
            x: 830,
            y: 60,
            width: 140,
            height: 70,
            text: 'STANDARDS.md',
            fontSize: 15,
            fontFamily: 1,
            textAlign: 'center',
            verticalAlign: 'middle',
            strokeColor: '#1e1e2e',
        },
        {
            id: 'el_cursorrules',
            type: 'ellipse',
            x: 830,
            y: 170,
            width: 140,
            height: 70,
            backgroundColor: '#f5c2e7',
            strokeColor: '#1e1e2e',
            fillStyle: 'hachure',
            strokeWidth: 2,
            roughness: 1,
            opacity: 100,
            boundElements: [{ id: 'txt_cursorrules', type: 'text' }],
        },
        {
            id: 'txt_cursorrules',
            type: 'text',
            containerId: 'el_cursorrules',
            x: 830,
            y: 170,
            width: 140,
            height: 70,
            text: '.cursorrules',
            fontSize: 15,
            fontFamily: 1,
            textAlign: 'center',
            verticalAlign: 'middle',
            strokeColor: '#1e1e2e',
        },
    ],
    appState: {
        currentItemFontFamily: 1,
    },
}
